CREATE TABLE products (
	id VARCHAR(40) NOT NULL PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	price BIGINT NOT NULL,
	weight INT8 NOT NULL,
	available BOOLEAN NOT NULL,
	deleted BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NOT NULL DEFAULT '1999-01-01 00:00:00'
);

CREATE TABLE ratings (
	id VARCHAR(40) NOT NULL PRIMARY KEY,
	product_id VARCHAR(40) NOT NULL,
	value INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
); 
